// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bonus.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterResponse_Status int32

const (
	RegisterResponse_INVALID               RegisterResponse_Status = 0
	RegisterResponse_OK                    RegisterResponse_Status = 1
	RegisterResponse_LOGIN_IN_USE          RegisterResponse_Status = 2
	RegisterResponse_INTERNAL_SERVEL_ERROR RegisterResponse_Status = 3
)

var RegisterResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "LOGIN_IN_USE",
	3: "INTERNAL_SERVEL_ERROR",
}

var RegisterResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"LOGIN_IN_USE":          2,
	"INTERNAL_SERVEL_ERROR": 3,
}

func (x RegisterResponse_Status) String() string {
	return proto.EnumName(RegisterResponse_Status_name, int32(x))
}

func (RegisterResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{1, 0}
}

type LoginResponse_Status int32

const (
	LoginResponse_INVALID               LoginResponse_Status = 0
	LoginResponse_OK                    LoginResponse_Status = 1
	LoginResponse_UNAUTHORIZED          LoginResponse_Status = 2
	LoginResponse_INTERNAL_SERVER_ERROR LoginResponse_Status = 3
)

var LoginResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "UNAUTHORIZED",
	3: "INTERNAL_SERVER_ERROR",
}

var LoginResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"UNAUTHORIZED":          2,
	"INTERNAL_SERVER_ERROR": 3,
}

func (x LoginResponse_Status) String() string {
	return proto.EnumName(LoginResponse_Status_name, int32(x))
}

func (LoginResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{3, 0}
}

type AuthResponse_Status int32

const (
	AuthResponse_INVALID               AuthResponse_Status = 0
	AuthResponse_OK                    AuthResponse_Status = 1
	AuthResponse_UNAUTHORIZED          AuthResponse_Status = 2
	AuthResponse_INTERNAL_SERVER_ERROR AuthResponse_Status = 3
)

var AuthResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "UNAUTHORIZED",
	3: "INTERNAL_SERVER_ERROR",
}

var AuthResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"UNAUTHORIZED":          2,
	"INTERNAL_SERVER_ERROR": 3,
}

func (x AuthResponse_Status) String() string {
	return proto.EnumName(AuthResponse_Status_name, int32(x))
}

func (AuthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{5, 0}
}

type UploadOrderResponse_Status int32

const (
	UploadOrderResponse_INVALID                          UploadOrderResponse_Status = 0
	UploadOrderResponse_OK                               UploadOrderResponse_Status = 1
	UploadOrderResponse_ALREADY_UPLOADED_BY_THIS_USER    UploadOrderResponse_Status = 2
	UploadOrderResponse_BAD_REQUEST                      UploadOrderResponse_Status = 3
	UploadOrderResponse_UNAUTHORIZED                     UploadOrderResponse_Status = 4
	UploadOrderResponse_ALREADY_UPLOADED_BY_ANOTHER_USER UploadOrderResponse_Status = 5
	UploadOrderResponse_BAD_ORDER_NUMBER                 UploadOrderResponse_Status = 6
	UploadOrderResponse_INTERNAL_SERVER_ERROR            UploadOrderResponse_Status = 7
)

var UploadOrderResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "ALREADY_UPLOADED_BY_THIS_USER",
	3: "BAD_REQUEST",
	4: "UNAUTHORIZED",
	5: "ALREADY_UPLOADED_BY_ANOTHER_USER",
	6: "BAD_ORDER_NUMBER",
	7: "INTERNAL_SERVER_ERROR",
}

var UploadOrderResponse_Status_value = map[string]int32{
	"INVALID":                          0,
	"OK":                               1,
	"ALREADY_UPLOADED_BY_THIS_USER":    2,
	"BAD_REQUEST":                      3,
	"UNAUTHORIZED":                     4,
	"ALREADY_UPLOADED_BY_ANOTHER_USER": 5,
	"BAD_ORDER_NUMBER":                 6,
	"INTERNAL_SERVER_ERROR":            7,
}

func (x UploadOrderResponse_Status) String() string {
	return proto.EnumName(UploadOrderResponse_Status_name, int32(x))
}

func (UploadOrderResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{7, 0}
}

type GetOrderListResponse_Status int32

const (
	GetOrderListResponse_INVALID               GetOrderListResponse_Status = 0
	GetOrderListResponse_OK                    GetOrderListResponse_Status = 1
	GetOrderListResponse_NO_DATA               GetOrderListResponse_Status = 2
	GetOrderListResponse_UNAUTHORIZED          GetOrderListResponse_Status = 3
	GetOrderListResponse_INTERNAL_SERVER_ERROR GetOrderListResponse_Status = 4
)

var GetOrderListResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "NO_DATA",
	3: "UNAUTHORIZED",
	4: "INTERNAL_SERVER_ERROR",
}

var GetOrderListResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"NO_DATA":               2,
	"UNAUTHORIZED":          3,
	"INTERNAL_SERVER_ERROR": 4,
}

func (x GetOrderListResponse_Status) String() string {
	return proto.EnumName(GetOrderListResponse_Status_name, int32(x))
}

func (GetOrderListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{10, 0}
}

type GetUserBalanceResponse_Status int32

const (
	GetUserBalanceResponse_INVALID               GetUserBalanceResponse_Status = 0
	GetUserBalanceResponse_OK                    GetUserBalanceResponse_Status = 1
	GetUserBalanceResponse_UNAUTHORIZED          GetUserBalanceResponse_Status = 2
	GetUserBalanceResponse_INTERNAL_SERVER_ERROR GetUserBalanceResponse_Status = 3
)

var GetUserBalanceResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "UNAUTHORIZED",
	3: "INTERNAL_SERVER_ERROR",
}

var GetUserBalanceResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"UNAUTHORIZED":          2,
	"INTERNAL_SERVER_ERROR": 3,
}

func (x GetUserBalanceResponse_Status) String() string {
	return proto.EnumName(GetUserBalanceResponse_Status_name, int32(x))
}

func (GetUserBalanceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{12, 0}
}

type WithdrawResponse_Status int32

const (
	WithdrawResponse_INVALID               WithdrawResponse_Status = 0
	WithdrawResponse_OK                    WithdrawResponse_Status = 1
	WithdrawResponse_UNAUTHORIZED          WithdrawResponse_Status = 2
	WithdrawResponse_INSUFFICIENT_FUNDS    WithdrawResponse_Status = 3
	WithdrawResponse_BAD_ORDER_NUMBER      WithdrawResponse_Status = 4
	WithdrawResponse_INTERNAL_SERVER_ERROR WithdrawResponse_Status = 5
)

var WithdrawResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "UNAUTHORIZED",
	3: "INSUFFICIENT_FUNDS",
	4: "BAD_ORDER_NUMBER",
	5: "INTERNAL_SERVER_ERROR",
}

var WithdrawResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"UNAUTHORIZED":          2,
	"INSUFFICIENT_FUNDS":    3,
	"BAD_ORDER_NUMBER":      4,
	"INTERNAL_SERVER_ERROR": 5,
}

func (x WithdrawResponse_Status) String() string {
	return proto.EnumName(WithdrawResponse_Status_name, int32(x))
}

func (WithdrawResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{14, 0}
}

type GetAllWithdrawalsByUserResponse_Status int32

const (
	GetAllWithdrawalsByUserResponse_INVALID               GetAllWithdrawalsByUserResponse_Status = 0
	GetAllWithdrawalsByUserResponse_OK                    GetAllWithdrawalsByUserResponse_Status = 1
	GetAllWithdrawalsByUserResponse_NO_DATA               GetAllWithdrawalsByUserResponse_Status = 2
	GetAllWithdrawalsByUserResponse_UNAUTHORIZED          GetAllWithdrawalsByUserResponse_Status = 3
	GetAllWithdrawalsByUserResponse_INTERNAL_SERVER_ERROR GetAllWithdrawalsByUserResponse_Status = 4
)

var GetAllWithdrawalsByUserResponse_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "NO_DATA",
	3: "UNAUTHORIZED",
	4: "INTERNAL_SERVER_ERROR",
}

var GetAllWithdrawalsByUserResponse_Status_value = map[string]int32{
	"INVALID":               0,
	"OK":                    1,
	"NO_DATA":               2,
	"UNAUTHORIZED":          3,
	"INTERNAL_SERVER_ERROR": 4,
}

func (x GetAllWithdrawalsByUserResponse_Status) String() string {
	return proto.EnumName(GetAllWithdrawalsByUserResponse_Status_name, int32(x))
}

func (GetAllWithdrawalsByUserResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{17, 0}
}

// Register user
type RegisterRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Status               RegisterResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.RegisterResponse_Status" json:"status,omitempty"`
	AuthToken            string                  `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetStatus() RegisterResponse_Status {
	if m != nil {
		return m.Status
	}
	return RegisterResponse_INVALID
}

func (m *RegisterResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

// Login user
type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status               LoginResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.LoginResponse_Status" json:"status,omitempty"`
	AuthToken            string               `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() LoginResponse_Status {
	if m != nil {
		return m.Status
	}
	return LoginResponse_INVALID
}

func (m *LoginResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

// Authenticate user
type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{4}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	Status               AuthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.AuthResponse_Status" json:"status,omitempty"`
	Username             string              `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{5}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetStatus() AuthResponse_Status {
	if m != nil {
		return m.Status
	}
	return AuthResponse_INVALID
}

func (m *AuthResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// Upload order
type UploadOrderRequest struct {
	Order                int64    `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadOrderRequest) Reset()         { *m = UploadOrderRequest{} }
func (m *UploadOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UploadOrderRequest) ProtoMessage()    {}
func (*UploadOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{6}
}

func (m *UploadOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadOrderRequest.Unmarshal(m, b)
}
func (m *UploadOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadOrderRequest.Marshal(b, m, deterministic)
}
func (m *UploadOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadOrderRequest.Merge(m, src)
}
func (m *UploadOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UploadOrderRequest.Size(m)
}
func (m *UploadOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadOrderRequest proto.InternalMessageInfo

func (m *UploadOrderRequest) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *UploadOrderRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UploadOrderResponse struct {
	Status               UploadOrderResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.UploadOrderResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UploadOrderResponse) Reset()         { *m = UploadOrderResponse{} }
func (m *UploadOrderResponse) String() string { return proto.CompactTextString(m) }
func (*UploadOrderResponse) ProtoMessage()    {}
func (*UploadOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{7}
}

func (m *UploadOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadOrderResponse.Unmarshal(m, b)
}
func (m *UploadOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadOrderResponse.Marshal(b, m, deterministic)
}
func (m *UploadOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadOrderResponse.Merge(m, src)
}
func (m *UploadOrderResponse) XXX_Size() int {
	return xxx_messageInfo_UploadOrderResponse.Size(m)
}
func (m *UploadOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadOrderResponse proto.InternalMessageInfo

func (m *UploadOrderResponse) GetStatus() UploadOrderResponse_Status {
	if m != nil {
		return m.Status
	}
	return UploadOrderResponse_INVALID
}

// Get order list
type GetOrderListRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderListRequest) Reset()         { *m = GetOrderListRequest{} }
func (m *GetOrderListRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderListRequest) ProtoMessage()    {}
func (*GetOrderListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{8}
}

func (m *GetOrderListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderListRequest.Unmarshal(m, b)
}
func (m *GetOrderListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderListRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderListRequest.Merge(m, src)
}
func (m *GetOrderListRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderListRequest.Size(m)
}
func (m *GetOrderListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderListRequest proto.InternalMessageInfo

func (m *GetOrderListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type OrderInfo struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Accrual              float32  `protobuf:"fixed32,3,opt,name=accrual,proto3" json:"accrual,omitempty"`
	UploadedAt           string   `protobuf:"bytes,4,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{9}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *OrderInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderInfo) GetAccrual() float32 {
	if m != nil {
		return m.Accrual
	}
	return 0
}

func (m *OrderInfo) GetUploadedAt() string {
	if m != nil {
		return m.UploadedAt
	}
	return ""
}

type GetOrderListResponse struct {
	Status               GetOrderListResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.GetOrderListResponse_Status" json:"status,omitempty"`
	OrderInfo            []*OrderInfo                `protobuf:"bytes,2,rep,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetOrderListResponse) Reset()         { *m = GetOrderListResponse{} }
func (m *GetOrderListResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderListResponse) ProtoMessage()    {}
func (*GetOrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{10}
}

func (m *GetOrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderListResponse.Unmarshal(m, b)
}
func (m *GetOrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderListResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderListResponse.Merge(m, src)
}
func (m *GetOrderListResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderListResponse.Size(m)
}
func (m *GetOrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderListResponse proto.InternalMessageInfo

func (m *GetOrderListResponse) GetStatus() GetOrderListResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetOrderListResponse_INVALID
}

func (m *GetOrderListResponse) GetOrderInfo() []*OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

// Get user balance
type GetUserBalanceRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBalanceRequest) Reset()         { *m = GetUserBalanceRequest{} }
func (m *GetUserBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserBalanceRequest) ProtoMessage()    {}
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{11}
}

func (m *GetUserBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBalanceRequest.Unmarshal(m, b)
}
func (m *GetUserBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetUserBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBalanceRequest.Merge(m, src)
}
func (m *GetUserBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserBalanceRequest.Size(m)
}
func (m *GetUserBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBalanceRequest proto.InternalMessageInfo

func (m *GetUserBalanceRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserBalanceResponse struct {
	Status               GetUserBalanceResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.GetUserBalanceResponse_Status" json:"status,omitempty"`
	Current              float32                       `protobuf:"fixed32,2,opt,name=current,proto3" json:"current,omitempty"`
	Withdrawn            float32                       `protobuf:"fixed32,3,opt,name=withdrawn,proto3" json:"withdrawn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetUserBalanceResponse) Reset()         { *m = GetUserBalanceResponse{} }
func (m *GetUserBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserBalanceResponse) ProtoMessage()    {}
func (*GetUserBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{12}
}

func (m *GetUserBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBalanceResponse.Unmarshal(m, b)
}
func (m *GetUserBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetUserBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBalanceResponse.Merge(m, src)
}
func (m *GetUserBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserBalanceResponse.Size(m)
}
func (m *GetUserBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBalanceResponse proto.InternalMessageInfo

func (m *GetUserBalanceResponse) GetStatus() GetUserBalanceResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetUserBalanceResponse_INVALID
}

func (m *GetUserBalanceResponse) GetCurrent() float32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *GetUserBalanceResponse) GetWithdrawn() float32 {
	if m != nil {
		return m.Withdrawn
	}
	return 0
}

// Withdraw request
type WithdrawRequest struct {
	Order                string   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Sum                  float32  `protobuf:"fixed32,2,opt,name=sum,proto3" json:"sum,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{13}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *WithdrawRequest) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *WithdrawRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type WithdrawResponse struct {
	Status               WithdrawResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.WithdrawResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{14}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetStatus() WithdrawResponse_Status {
	if m != nil {
		return m.Status
	}
	return WithdrawResponse_INVALID
}

// Get all withdrawals
type GetAllWithdrawalsByUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllWithdrawalsByUserRequest) Reset()         { *m = GetAllWithdrawalsByUserRequest{} }
func (m *GetAllWithdrawalsByUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllWithdrawalsByUserRequest) ProtoMessage()    {}
func (*GetAllWithdrawalsByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{15}
}

func (m *GetAllWithdrawalsByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllWithdrawalsByUserRequest.Unmarshal(m, b)
}
func (m *GetAllWithdrawalsByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllWithdrawalsByUserRequest.Marshal(b, m, deterministic)
}
func (m *GetAllWithdrawalsByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllWithdrawalsByUserRequest.Merge(m, src)
}
func (m *GetAllWithdrawalsByUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllWithdrawalsByUserRequest.Size(m)
}
func (m *GetAllWithdrawalsByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllWithdrawalsByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllWithdrawalsByUserRequest proto.InternalMessageInfo

func (m *GetAllWithdrawalsByUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Withdrawal struct {
	Order                string   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Sum                  float32  `protobuf:"fixed32,2,opt,name=sum,proto3" json:"sum,omitempty"`
	ProcessedAt          string   `protobuf:"bytes,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Withdrawal) Reset()         { *m = Withdrawal{} }
func (m *Withdrawal) String() string { return proto.CompactTextString(m) }
func (*Withdrawal) ProtoMessage()    {}
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{16}
}

func (m *Withdrawal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdrawal.Unmarshal(m, b)
}
func (m *Withdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdrawal.Marshal(b, m, deterministic)
}
func (m *Withdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdrawal.Merge(m, src)
}
func (m *Withdrawal) XXX_Size() int {
	return xxx_messageInfo_Withdrawal.Size(m)
}
func (m *Withdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_Withdrawal proto.InternalMessageInfo

func (m *Withdrawal) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *Withdrawal) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *Withdrawal) GetProcessedAt() string {
	if m != nil {
		return m.ProcessedAt
	}
	return ""
}

type GetAllWithdrawalsByUserResponse struct {
	Status               GetAllWithdrawalsByUserResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=service.GetAllWithdrawalsByUserResponse_Status" json:"status,omitempty"`
	WithdrawalInfo       []*Withdrawal                          `protobuf:"bytes,2,rep,name=withdrawal_info,json=withdrawalInfo,proto3" json:"withdrawal_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetAllWithdrawalsByUserResponse) Reset()         { *m = GetAllWithdrawalsByUserResponse{} }
func (m *GetAllWithdrawalsByUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllWithdrawalsByUserResponse) ProtoMessage()    {}
func (*GetAllWithdrawalsByUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83825e3ca88f3ef, []int{17}
}

func (m *GetAllWithdrawalsByUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllWithdrawalsByUserResponse.Unmarshal(m, b)
}
func (m *GetAllWithdrawalsByUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllWithdrawalsByUserResponse.Marshal(b, m, deterministic)
}
func (m *GetAllWithdrawalsByUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllWithdrawalsByUserResponse.Merge(m, src)
}
func (m *GetAllWithdrawalsByUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllWithdrawalsByUserResponse.Size(m)
}
func (m *GetAllWithdrawalsByUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllWithdrawalsByUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllWithdrawalsByUserResponse proto.InternalMessageInfo

func (m *GetAllWithdrawalsByUserResponse) GetStatus() GetAllWithdrawalsByUserResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetAllWithdrawalsByUserResponse_INVALID
}

func (m *GetAllWithdrawalsByUserResponse) GetWithdrawalInfo() []*Withdrawal {
	if m != nil {
		return m.WithdrawalInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("service.RegisterResponse_Status", RegisterResponse_Status_name, RegisterResponse_Status_value)
	proto.RegisterEnum("service.LoginResponse_Status", LoginResponse_Status_name, LoginResponse_Status_value)
	proto.RegisterEnum("service.AuthResponse_Status", AuthResponse_Status_name, AuthResponse_Status_value)
	proto.RegisterEnum("service.UploadOrderResponse_Status", UploadOrderResponse_Status_name, UploadOrderResponse_Status_value)
	proto.RegisterEnum("service.GetOrderListResponse_Status", GetOrderListResponse_Status_name, GetOrderListResponse_Status_value)
	proto.RegisterEnum("service.GetUserBalanceResponse_Status", GetUserBalanceResponse_Status_name, GetUserBalanceResponse_Status_value)
	proto.RegisterEnum("service.WithdrawResponse_Status", WithdrawResponse_Status_name, WithdrawResponse_Status_value)
	proto.RegisterEnum("service.GetAllWithdrawalsByUserResponse_Status", GetAllWithdrawalsByUserResponse_Status_name, GetAllWithdrawalsByUserResponse_Status_value)
	proto.RegisterType((*RegisterRequest)(nil), "service.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "service.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "service.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "service.LoginResponse")
	proto.RegisterType((*AuthRequest)(nil), "service.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "service.AuthResponse")
	proto.RegisterType((*UploadOrderRequest)(nil), "service.UploadOrderRequest")
	proto.RegisterType((*UploadOrderResponse)(nil), "service.UploadOrderResponse")
	proto.RegisterType((*GetOrderListRequest)(nil), "service.GetOrderListRequest")
	proto.RegisterType((*OrderInfo)(nil), "service.OrderInfo")
	proto.RegisterType((*GetOrderListResponse)(nil), "service.GetOrderListResponse")
	proto.RegisterType((*GetUserBalanceRequest)(nil), "service.GetUserBalanceRequest")
	proto.RegisterType((*GetUserBalanceResponse)(nil), "service.GetUserBalanceResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "service.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "service.WithdrawResponse")
	proto.RegisterType((*GetAllWithdrawalsByUserRequest)(nil), "service.GetAllWithdrawalsByUserRequest")
	proto.RegisterType((*Withdrawal)(nil), "service.Withdrawal")
	proto.RegisterType((*GetAllWithdrawalsByUserResponse)(nil), "service.GetAllWithdrawalsByUserResponse")
}

func init() { proto.RegisterFile("bonus.proto", fileDescriptor_b83825e3ca88f3ef) }

var fileDescriptor_b83825e3ca88f3ef = []byte{
	// 924 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xc1, 0x6e, 0xe3, 0x54,
	0x14, 0xc5, 0x76, 0x9b, 0x34, 0x37, 0x61, 0x6a, 0xbd, 0x76, 0xaa, 0x4c, 0xd4, 0xd2, 0x8c, 0x67,
	0x84, 0xba, 0x6a, 0xa0, 0x03, 0x12, 0x12, 0x15, 0xc2, 0x19, 0xbb, 0xa9, 0x21, 0xd8, 0xf0, 0x12,
	0x4f, 0x35, 0xc3, 0xc2, 0x72, 0x93, 0x37, 0xad, 0x35, 0x8e, 0x1d, 0xfc, 0x9e, 0xa7, 0xb0, 0x84,
	0x1f, 0x60, 0xc1, 0x6f, 0xb0, 0x61, 0x85, 0xc4, 0x07, 0xf0, 0x03, 0x6c, 0x91, 0xd8, 0xf0, 0x21,
	0xc8, 0xf6, 0xb3, 0x93, 0xb8, 0x49, 0x29, 0xa8, 0xb3, 0xcb, 0x7d, 0x3e, 0xef, 0xfa, 0x9e, 0x73,
	0xee, 0x8d, 0x2f, 0xd4, 0xcf, 0xc3, 0x20, 0xa6, 0x87, 0xd3, 0x28, 0x64, 0x21, 0xaa, 0x52, 0x12,
	0xbd, 0xf6, 0x46, 0xa4, 0xb5, 0x7b, 0x11, 0x86, 0x17, 0x3e, 0xe9, 0xb8, 0x53, 0xaf, 0xe3, 0x06,
	0x41, 0xc8, 0x5c, 0xe6, 0x85, 0x01, 0x87, 0xb5, 0xf6, 0xf9, 0xd3, 0x34, 0x3a, 0x8f, 0x5f, 0x76,
	0x98, 0x37, 0x21, 0x94, 0xb9, 0x93, 0x69, 0x06, 0x50, 0x9e, 0xc2, 0x26, 0x26, 0x17, 0x1e, 0x65,
	0x24, 0xc2, 0xe4, 0x9b, 0x98, 0x50, 0x86, 0xb6, 0x61, 0xdd, 0x0f, 0x2f, 0xbc, 0xa0, 0x29, 0xb4,
	0x85, 0x83, 0x1a, 0xce, 0x02, 0xd4, 0x82, 0x8d, 0xa9, 0x4b, 0xe9, 0x55, 0x18, 0x8d, 0x9b, 0x62,
	0xfa, 0xa0, 0x88, 0x95, 0x5f, 0x05, 0x90, 0x67, 0x59, 0xe8, 0x34, 0x0c, 0x28, 0x41, 0x1f, 0x41,
	0x85, 0x32, 0x97, 0xc5, 0x34, 0xcd, 0x73, 0xef, 0xa8, 0x7d, 0xc8, 0x4b, 0x3e, 0x2c, 0x43, 0x0f,
	0x07, 0x29, 0x0e, 0x73, 0x3c, 0xda, 0x03, 0x70, 0x63, 0x76, 0xe9, 0xb0, 0xf0, 0x15, 0x09, 0xf8,
	0xcb, 0x6a, 0xc9, 0xc9, 0x30, 0x39, 0x50, 0x3e, 0x83, 0x4a, 0x76, 0x01, 0xd5, 0xa1, 0x6a, 0x98,
	0xcf, 0xd4, 0xbe, 0xa1, 0xc9, 0x6f, 0xa1, 0x0a, 0x88, 0xd6, 0xe7, 0xb2, 0x80, 0x64, 0x68, 0xf4,
	0xad, 0x9e, 0x61, 0x3a, 0x86, 0xe9, 0xd8, 0x03, 0x5d, 0x16, 0xd1, 0x03, 0xb8, 0x6f, 0x98, 0x43,
	0x1d, 0x9b, 0x6a, 0xdf, 0x19, 0xe8, 0xf8, 0x99, 0xde, 0x77, 0x74, 0x8c, 0x2d, 0x2c, 0x4b, 0xca,
	0xa7, 0xd0, 0xe8, 0x27, 0xf4, 0xfe, 0x3f, 0xf7, 0x5f, 0x04, 0x78, 0x9b, 0xa7, 0xe0, 0xc4, 0x3f,
	0x2c, 0x11, 0xdf, 0x2b, 0x88, 0x2f, 0xe0, 0xee, 0x9c, 0xb5, 0x6d, 0xaa, 0xf6, 0xf0, 0xd4, 0xc2,
	0xc6, 0x0b, 0x5d, 0x5b, 0xc6, 0x1a, 0x17, 0xac, 0x1f, 0x41, 0x5d, 0x8d, 0xd9, 0xe5, 0x1c, 0xe9,
	0xec, 0xa5, 0x9c, 0x74, 0x1a, 0x28, 0x3f, 0x0b, 0xd0, 0xc8, 0x50, 0x9c, 0xd7, 0x07, 0x25, 0x5e,
	0xbb, 0x05, 0xaf, 0x79, 0x58, 0x99, 0x56, 0x0b, 0x36, 0x62, 0x4a, 0xa2, 0xc0, 0x9d, 0x90, 0x5c,
	0xbb, 0x3c, 0xbe, 0x53, 0x4e, 0x27, 0x80, 0xec, 0xa9, 0x1f, 0xba, 0x63, 0x2b, 0x1a, 0x2f, 0xf4,
	0x72, 0x98, 0xc4, 0x69, 0xc9, 0x12, 0xce, 0x82, 0x1b, 0x6b, 0xfa, 0x51, 0x84, 0xad, 0x85, 0x44,
	0x9c, 0xfd, 0xc7, 0x25, 0xf6, 0x8f, 0x0a, 0xf6, 0x4b, 0xd0, 0x25, 0x11, 0x94, 0xdf, 0x84, 0x9b,
	0x99, 0x3e, 0x84, 0x3d, 0xb5, 0x8f, 0x75, 0x55, 0x7b, 0xee, 0xd8, 0x5f, 0xf6, 0x2d, 0x55, 0xd3,
	0x35, 0xa7, 0xfb, 0xdc, 0x19, 0x9e, 0x1a, 0x83, 0xa4, 0x87, 0xb1, 0x2c, 0xa2, 0x4d, 0xa8, 0x77,
	0x55, 0xcd, 0xc1, 0xfa, 0x57, 0xb6, 0x3e, 0x18, 0xca, 0xd2, 0x35, 0x75, 0xd6, 0xd0, 0x63, 0x68,
	0x2f, 0xcb, 0xa2, 0x9a, 0xd6, 0xf0, 0x54, 0xc7, 0x59, 0xa2, 0x75, 0xb4, 0x0d, 0x72, 0x92, 0xc8,
	0xc2, 0x9a, 0x8e, 0x1d, 0xd3, 0xfe, 0xa2, 0xab, 0x63, 0xb9, 0xb2, 0x5a, 0xd9, 0xaa, 0xf2, 0x3e,
	0x6c, 0xf5, 0x08, 0x4b, 0xf9, 0xf5, 0x3d, 0xca, 0x72, 0x69, 0xe7, 0x45, 0x14, 0x4a, 0x22, 0xbe,
	0x86, 0x5a, 0x8a, 0x37, 0x82, 0x97, 0x21, 0xda, 0x81, 0x4a, 0x10, 0x4f, 0xce, 0xb9, 0x09, 0x35,
	0xcc, 0xa3, 0xe4, 0x9c, 0x2b, 0x9a, 0x79, 0x90, 0x77, 0x4c, 0x13, 0xaa, 0xee, 0x68, 0x14, 0xc5,
	0xae, 0xdf, 0x94, 0xda, 0xc2, 0x81, 0x88, 0xf3, 0x10, 0xed, 0x43, 0x3d, 0x4e, 0xc5, 0x26, 0x63,
	0xc7, 0x65, 0xcd, 0xb5, 0xf4, 0x1a, 0xe4, 0x47, 0x2a, 0x53, 0xfe, 0x12, 0x60, 0x7b, 0xb1, 0x56,
	0xee, 0xde, 0x71, 0xc9, 0xbd, 0xc7, 0x85, 0x7b, 0xcb, 0xe0, 0xe5, 0x1e, 0x7e, 0x0f, 0x6a, 0x61,
	0x4e, 0xa7, 0x29, 0xb6, 0xa5, 0x83, 0xfa, 0x11, 0x2a, 0x12, 0x14, 0x44, 0xf1, 0x0c, 0xa4, 0x9c,
	0xdd, 0xec, 0x77, 0x1d, 0xaa, 0xa6, 0xe5, 0x68, 0xea, 0x50, 0x95, 0xc5, 0x6b, 0x46, 0x4a, 0xab,
	0xcd, 0x58, 0x53, 0x9e, 0xc0, 0xfd, 0x1e, 0x61, 0x36, 0x25, 0x51, 0xd7, 0xf5, 0xdd, 0x60, 0x44,
	0x6e, 0x63, 0xc7, 0x9f, 0x02, 0xec, 0x94, 0x6f, 0x71, 0x61, 0x3e, 0x29, 0x09, 0xf3, 0xee, 0xbc,
	0x30, 0x4b, 0x2e, 0x94, 0xa5, 0x69, 0x42, 0x75, 0x14, 0x47, 0x11, 0x09, 0x58, 0xea, 0xa2, 0x88,
	0xf3, 0x10, 0xed, 0x42, 0xed, 0xca, 0x63, 0x97, 0xe3, 0xc8, 0xbd, 0x0a, 0xb8, 0x91, 0xb3, 0x83,
	0x3b, 0x1d, 0x7d, 0x1b, 0x36, 0xcf, 0x78, 0xe2, 0xa5, 0x73, 0x5f, 0xcb, 0xe7, 0x5e, 0x06, 0x89,
	0xc6, 0x13, 0x5e, 0x68, 0xf2, 0x73, 0x41, 0x35, 0xa9, 0xa4, 0xda, 0xef, 0x02, 0xc8, 0xb3, 0xbc,
	0xff, 0xfa, 0x55, 0x2b, 0x43, 0xcb, 0xff, 0x01, 0xdf, 0xfe, 0x57, 0xc6, 0x3b, 0x80, 0x0c, 0x73,
	0x60, 0x9f, 0x9c, 0x18, 0x4f, 0x0d, 0xdd, 0x1c, 0x3a, 0x27, 0xb6, 0xa9, 0x0d, 0x64, 0x69, 0xe9,
	0x00, 0xaf, 0xad, 0xd6, 0x67, 0x5d, 0x39, 0x86, 0x77, 0x7a, 0x84, 0xa9, 0xbe, 0x9f, 0x97, 0xe8,
	0xfa, 0xb4, 0xfb, 0x5d, 0x62, 0xee, 0x6d, 0x9a, 0xe7, 0x0c, 0x60, 0x76, 0xef, 0xd6, 0xc2, 0x3e,
	0x84, 0xc6, 0x34, 0x0a, 0x47, 0x84, 0xd2, 0x6c, 0x56, 0x33, 0x71, 0xeb, 0xc5, 0x99, 0xca, 0x94,
	0xef, 0x45, 0xd8, 0x5f, 0x59, 0x17, 0x97, 0xbb, 0x57, 0x92, 0xbb, 0x33, 0xdf, 0x9e, 0x37, 0xdd,
	0x2c, 0xf7, 0xe9, 0x31, 0x6c, 0x5e, 0x15, 0x58, 0xc7, 0x9b, 0x0d, 0xf2, 0xd6, 0x35, 0x03, 0x5d,
	0x1f, 0xdf, 0x9b, 0x61, 0xdf, 0xe8, 0x38, 0x1f, 0xbd, 0x82, 0x46, 0x37, 0xd9, 0xea, 0x06, 0x59,
	0x0d, 0xe8, 0x6b, 0xd8, 0xc8, 0xb7, 0x23, 0xd4, 0x5c, 0xb2, 0x30, 0xa5, 0x76, 0xb5, 0x1e, 0xac,
	0x5c, 0xa5, 0x94, 0xd6, 0x0f, 0x7f, 0xfc, 0xfd, 0x93, 0xb8, 0xad, 0xa0, 0x74, 0x21, 0x4c, 0x4c,
	0xec, 0x44, 0x1c, 0xd3, 0xad, 0xbd, 0xc8, 0xb7, 0xc6, 0xf3, 0x4a, 0xba, 0xfd, 0x3d, 0xf9, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x81, 0x18, 0x38, 0xdc, 0x54, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BonusServiceClient is the client API for BonusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BonusServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type bonusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBonusServiceClient(cc grpc.ClientConnInterface) BonusServiceClient {
	return &bonusServiceClient{cc}
}

func (c *bonusServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/service.BonusService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BonusServiceServer is the server API for BonusService service.
type BonusServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedBonusServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBonusServiceServer struct {
}

func (*UnimplementedBonusServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterBonusServiceServer(s *grpc.Server, srv BonusServiceServer) {
	s.RegisterService(&_BonusService_serviceDesc, srv)
}

func _BonusService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.BonusService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BonusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.BonusService",
	HandlerType: (*BonusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _BonusService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bonus.proto",
}
